---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r tsa-data, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}
library(tidyverse)

xml2::read_html("https://www.tsa.gov/coronavirus/passenger-throughput") %>% 
  rvest::html_table(header = TRUE, fill = TRUE) %>% 
  pluck(1) %>% 
  as_tibble() %>% 
  docxtractr::mcga() %>% 
  filter(!is.na(date)) %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  print() -> raw

bind_rows(
  raw[c(1, 3)] %>% 
    mutate(date = date - lubridate::years()) %>% 
    rename(total_traveler_throughput = total_traveler_throughput_1_year_ago_same_weekday),
  raw[c(1, 2)]
) %>% 
  mutate(total_traveler_throughput = total_traveler_throughput %>% 
           stringr::str_remove_all(",") %>% 
           as.integer()) %>% 
  mutate(year = format(date, "%Y")) %>% 
  select(date, year, total_traveler_throughput) %>% 
  print() -> tsa
```

```{r tsa-plot, echo = FALSE, message = FALSE, warning = FALSE, include = TRUE}
tsa %>% 
  mutate(common_date = as.Date(paste0("2000-", format(date, "%j")), "%Y-%j")) %>% 
  ggplot(aes(x = common_date, y = total_traveler_throughput, 
             colour = year, shape = year)) +
  geom_path() +
  hrbrthemes::theme_ipsum_rc() +
  hrbrthemes::scale_y_comma() +
  scale_x_date(labels = function(x) format(x, "%d-%b")) +
  labs(x = NULL, y = NULL,
       title = "That was then, this is now, air traveler edition",
       subtitle = "TSA checkpoint travel numbers for 2020 and 2019",
       caption = "Source: https://www.tsa.gov/coronavirus/passenger-throughput") +
  theme(legend.title = element_blank(),
        legend.position = c(0.82, 0.6))
```
